name: MTVehicles
version: ${project.version}
main: nl.mtvehicles.core.Main
api-version: 1.13
softdepend: [ WorldGuard, Vault, PlaceholderAPI, Skript ]
commands:
  minetopiavehicles:
    usage: /minetopiavehicles
    aliases: [ mtv, minetopiav, mtvehicles, mtvehicle, vehicle ]
